// <auto-generated />
using System;
using CIS174_TestCoreApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIS174_TestCoreApp.Migrations.ErrorLog
{
    [DbContext(typeof(ErrorLogContext))]
    [Migration("20191107050956_ErrorLog")]
    partial class ErrorLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS174_TestCoreApp.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExceptionMessage");

                    b.Property<int>("HttpStatusCode");

                    b.Property<string>("StackTrace");

                    b.Property<DateTime>("TimeOfError");

                    b.HasKey("RequestId");

                    b.ToTable("ErrorLog");
                });
#pragma warning restore 612, 618
        }
    }
}
